service: api-snaps-service-${self:custom.projectName}
frameworkVersion: ">=1.44.0"

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  projectName: ${file(../../serverless.common.yml):custom.projectName}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  environment:
    tableName: ${file(../../serverless.common.yml):custom.generalTableName}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-${self:custom.projectName}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-${self:custom.projectName}-ApiGatewayRestApiRootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - sns:Publish
      Resource:
        - '*'

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-step-functions

functions:
  getAllSnaps:
    handler: src/handler.getAllSnaps
    events:
      - http:
          path: /snaps/{username}
          method: get
          cors: true
  createSnap:
    handler: src/handler.createSnap
  viewSnap:
    handler: src/handler.viewSnap
  publishSnap:
    handler: src/handler.publishSnap

stepFunctions:
  stateMachines:
    createSnapStepFunc:
      events:
        - http:
            path: /snaps
            method: post
            cors: true
      definition:
        Comment: "Create Snap Flow"
        StartAt: CreateSnap
        States:
          CreateSnap:
            Type: Task
            Resource: arn:aws:lambda:eu-west-1:068475715603:function:api-snaps-service-SnapGroups-dev-createSnap
            Next: PublishSnap
          PublishSnap:
            Type: Task
            Resource: arn:aws:lambda:eu-west-1:068475715603:function:api-snaps-service-SnapGroups-dev-publishSnap
            End: true
    viewSnapStepFunc:
      events:
        - http:
            path: /snaps/view
            method: put
            cors: true
      definition:
        Comment: "View Snap Flow"
        StartAt: ViewSnap
        States:
          ViewSnap:
            Type: Task
            Resource: arn:aws:lambda:eu-west-1:068475715603:function:api-snaps-service-SnapGroups-dev-viewSnap
            Next: PublishSnap
          PublishSnap:
            Type: Task
            Resource: arn:aws:lambda:eu-west-1:068475715603:function:api-snaps-service-SnapGroups-dev-publishSnap
            End: true
